#!/bin/bash

case $BLOCK_BUTTON in
    1) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;   # left click
    4) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;    # scroll up
    5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;    # scroll down
esac

VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5; exit}')
MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

if [ "$MUTE" = "yes" ]; then
    echo " Mute"
else
    echo " $VOL"
fi
